-- Arquivo de Migração Inicial para o Projeto OPIDAS

-- Tabela de Perfis de Usuários
-- Armazena dados públicos e específicos da aplicação para cada usuário.
create table public.profiles (
  id uuid not null primary key references auth.users(id) on delete cascade,
  first_name text,
  last_name text,
  avatar_url text,
  habit text,
  onboarding_status text default 'started', -- 'started', 'completed'
  last_habit_date date,
  retention_days integer default 0,
  rank text default 'recruta',
  remaining_resets integer default 5,
  is_blocked boolean default false,
  block_end_date timestamp with time zone,
  
  -- Campos de assinatura Stripe
  stripe_customer_id text,
  stripe_subscription_id text,
  subscription_status text -- 'trialing', 'active', 'past_due', 'canceled'
);

-- Habilita Row Level Security (RLS) para a tabela de perfis
alter table public.profiles enable row level security;

-- Política: Usuários podem ver o próprio perfil.
create policy "User can view their own profile." on public.profiles
  for select using (auth.uid() = id);

-- Política: Usuários podem atualizar o próprio perfil.
create policy "User can update their own profile." on public.profiles
  for update using (auth.uid() = id);

-- Gatilho para criar um perfil quando um novo usuário se registra
create function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id)
  values (new.id);
  return new;
end;
$$ language plpgsql security definer;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();


-- Tabela de Mensagens do Chat
create table public.messages (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  channel_id text not null, -- 'recruta', 'soldado', etc.
  content text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.messages enable row level security;

-- Política: Usuários autenticados podem ver todas as mensagens.
-- (Pode ser refinado para permitir ver apenas mensagens de patentes iguais ou inferiores)
create policy "Authenticated users can view messages." on public.messages
  for select using (auth.role() = 'authenticated');

-- Política: Usuários podem inserir mensagens.
create policy "Users can insert their own messages." on public.messages
  for insert with check (auth.uid() = user_id);

-- Habilita publicações em tempo real para a tabela de mensagens
alter publication supabase_realtime add table public.messages;


-- Tabela de Progresso de Vídeos
create table public.video_progress (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  episode_id integer not null,
  progress_percentage real default 0,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique (user_id, episode_id) -- Garante uma entrada por usuário/episódio
);

alter table public.video_progress enable row level security;

-- Política: Usuários podem ver e modificar seu próprio progresso de vídeo.
create policy "Users can manage their own video progress." on public.video_progress
  for all using (auth.uid() = user_id);